export default {
    tutorial: [
        "The satisfaction of checking things off your To Do list...",
        "Minus the work of actually doing them.",
        "Each day you get six new low-effort tasks.",
        "Swipe to mark them done.\nTry it now",
        "Swipe down for settings",
        "Finish this list to get started"
    ],
    basic: [
        "Leave the house",
        "Tell someone a joke",
        "Change into something more comfortable",
        "Wash your hands for as long as it takes you to sing 'Happy Birthday'",
        "Respond to one email",
        "Throw away all the mismatched socks in your drawer",
        "Eat breakfast",
        "Wear your favorite jeans",
        "Clean up your computer desktop",
        "Clean your laptop screen",
        "Schedule an appointment",
        "Listen to a Podcast while cleaning",
        "Comment something positive on a social media post",
        "Send a selfie to a friend",
        "Cut your nails or clean your ears",
        "Watch one movie that people cringe when you tell them you haven't seen",
        "Put on pants",
        "Drink a glass of water",
        "Check your email",
        "Get out of bed",
        "Take a dump",
        "Brush your teeth",
        "Check what's in the fridge",
        "Open The Least Dangerous To Do List app",
        "Find your keys",
        "Yell short sentences without the letter 'A' in them",
        "Anwswer a Robo-Call and press '2' to unsubscribe",
        "Wear matching socks",
        "Complete all tasks for today",
        "Check off a task you haven't actually completed",
        "Look into the mirror and compliment yourself",
        "Strech for 15 seconds",
        "Take a deep breath",
        "Ignore someone's advice",
        "Sit up straight",
        "Clear your browser history",
        "Close all open tabs of articles you haven't read yet",
        "Throw out something in your fridge",
        "Stare out of the window",
        "Think about how different your life could have been",
        "Clean your ears",
        "Clip your nails",
        "Send a selfie to a parent",
        "Feel okay about not flossing",
        "Read a random Wikipedia articles",
        "Flake out on your evening plans",
        "Clean the lint trap of your dryer",
        "Restart your laptop",
        "Delete an app you haven't used in a month",
        "Use an emoji you've never used before",
        "Change your toothbrush",
        "Make plans with a friend",
        "Eat something that does not suck",
        "Eat in bed",
        "Unfriend a negative jerk on Facebook",
        "Don't read the news today",
        "Don't think about Trump",
    ]
}
