export default {
    tutorial: [
        "The satisfaction of checking things off your To Do list...",
        "Minus the work of actually doing them.",
        "Each day you get six new low-effort tasks.",
        "Swipe to mark them done.\nTry it now",
        "Swipe down for settings tldtdl://review",
        "Finish this list to get started"
    ],
    basic: [
        "Leave the house",
        "Tell someone a joke",
        "Change into something more comfortable",
        "Wash your hands for as long as it takes you to sing 'Happy Birthday'",
        "Respond to one email",
        "Throw away all the mismatched socks in your drawer",
        "Eat breakfast",
        "Wear your favorite jeans",
        "Clean up your computer desktop",
        "Clean your laptop screen",
        "Schedule an appointment",
        "Listen to a Podcast while cleaning",
        "Comment something positive on a social media post",
        "Send a selfie to a friend",
        "Cut your nails or clean your ears",
        "Watch one movie that people cringe when you tell them you haven't seen",
        "Put on pants",
        "Drink a glass of water",
        "Check your email",
        "Get out of bed",
        "Take a dump",
        "Brush your teeth",
        "Check what's in the fridge",
        "Open The Least Dangerous To Do List app",
        "Find your keys",
        "Yell short sentences without the letter 'A' in them",
        "Anwswer a Robo-Call and press '2' to unsubscribe",
        "Wear matching socks",
        "Complete all tasks for today",
        "Check off a task you haven't actually completed",
        "Look into the mirror and compliment yourself",
        "Do a 15 second calf stretch",
        "Take one deep breath",
        "Ignore someone's advice",
        "Sit up straight, right now",
        "Clear your browser history",
        "Close all the open tabls of articles you haven't read yet",
        "Throw away something in your fridge",
        "Self a selfie to a parent",
        "Don't today. And don't feel guilty about it",
        "Read a random Wikipedia article https://en.wikipedia.org/wiki/Special:Random",
        "Flake out on your plans tonight and do something lazy",
        "Clean the lint trap in your dryer",
        "Restart your computer",
        "Restart your phone",
        "Charge your phone",
        "Give this app a 5 star rating ;) tldtdl://review",
        "Use an emoji you've never used before",
        "Change your toothbrush head or entire toothbrush",
        "Make plans with someone",
        "Eat one thing that isn't brown",
        "Unfollow the first person in your FB feed who posts something negative",
        "Don't check the news today",
        "Don't think about Trump",
        "Think about how different your life could have been",
        "Clean your ears",
        "Clip your nails",
        "Feel okay about not flossing",
        "Delete an app you haven't used in a month"
    ]
};
